/*eslint-disable*/
import React from "react";
import { Card, CardHeader, CardBody, CardTitle, Row, Col, Table } from "reactstrap";

class CurrentStudents extends React.Component {
  render() {
    return (
      <div className="content">
      <Row>
        <Col xs={10}>
            <Card>
              <CardHeader>
                <CardTitle tag="h4">Mentor-Mentee</CardTitle>
              </CardHeader>
              <CardBody>
              <Table responsive>
                <thead className=" text-primary">
                  <th>
                    Mentor Email
                  </th>
                  <th>
                    Mentee Email
                  </th>
                  <th>
                    Compatibility
                  </th>
                </thead>
                <tbody>
                  <tr>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      78%
                    </td>
                  </tr>
                  <tr>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      75%
                    </td>
                  </tr>
                  <tr>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      82%
                    </td>
                  </tr>
                  <tr>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      78%
                    </td>
                  </tr>
                  <tr>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      88%
                    </td>
                  </tr>
                  <tr>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      88%
                    </td>
                  </tr>
                  <tr>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      88%
                    </td>
                  </tr>
                  <tr>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      88%
                    </td>
                  </tr>
                </tbody>
              </Table>
              </CardBody>
            </Card>
          </Col>
      </Row>
      <Row>
        <Col xs={10}>
            <Card>
              <CardHeader>
                <CardTitle tag="h4">Mentor</CardTitle>
              </CardHeader>
              <CardBody>
              <Table responsive>
              <thead className=" text-primary">
                  <th>
                    Email
                  </th>
                  <th>
                    First Name
                  </th>
                  <th>
                    Preferred Name
                  </th>
                  <th>
                    Last Name
                  </th>
                  <th>
                    Interest 1
                  </th>
                  <th>
                    Interest 2
                  </th>
                  <th>
                    Interest 3
                  </th>
                  <th>
                    Interest 4
                  </th>
                  <th>
                    Interest 5
                  </th>
                  <th>
                    Year
                  </th>
                  <th>
                    Gender
                  </th>
                  <th>
                    Prefer same gender?
                  </th>
                </thead>
                <tbody>
                  <tr>
                    <td>
                      k1763918@kcl.ac.uk
                    </td>
                    <td>
                      Mananchaya
                    </td>
                    <td>
                      Mai
                    </td>
                    <td>
                      Khumtai
                    </td>
                    <td>
                      Cooking
                    </td>
                    <td>
                      Yoga
                    </td>
                    <td>
                      History
                    </td>
                    <td>
                      Japanese
                    </td>
                    <td>
                      Web development
                    </td>
                    <td>
                      Second
                    </td>
                    <td>
                      Female
                    </td>
                    <td>
                      No
                    </td>
                  </tr>
                  <tr>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      Jason
                    </td>
                    <td>
                      Jay
                    </td>
                    <td>
                      Steele
                    </td>
                    <td>
                      Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                      Third
                    </td>
                    <td>
                      Male
                    </td>
                    <td>
                      No
                    </td>
                  </tr>
                  <tr>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      Jason
                    </td>
                    <td>
                      Jay
                    </td>
                    <td>
                      Steele
                    </td>
                    <td>
                      Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                      Third
                    </td>
                    <td>
                      Male
                    </td>
                    <td>
                      No
                    </td>
                  </tr>
                  <tr>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      Jason
                    </td>
                    <td>
                      Jay
                    </td>
                    <td>
                      Steele
                    </td>
                    <td>
                      Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                      Third
                    </td>
                    <td>
                      Male
                    </td>
                    <td>
                      No
                    </td>
                  </tr>
                  <tr>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      Jason
                    </td>
                    <td>
                      Jay
                    </td>
                    <td>
                      Steele
                    </td>
                    <td>
                      Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                      Third
                    </td>
                    <td>
                      Male
                    </td>
                    <td>
                      No
                    </td>
                  </tr>
                </tbody>
              </Table>
              </CardBody>
            </Card>
          </Col>
      </Row>
      <Row>
        <Col xs={10}>
            <Card>
              <CardHeader>
                <CardTitle tag="h4">Mentee</CardTitle>
              </CardHeader>
              <CardBody>
              <Table responsive>
              <thead className=" text-primary">
                  <th>
                    Email
                  </th>
                  <th>
                    First Name
                  </th>
                  <th>
                    Preferred Name
                  </th>
                  <th>
                    Last Name
                  </th>
                  <th>
                    Interest 1
                  </th>
                  <th>
                    Interest 2
                  </th>
                  <th>
                    Interest 3
                  </th>
                  <th>
                    Interest 4
                  </th>
                  <th>
                    Interest 5
                  </th>
                  <th>
                    Year
                  </th>
                  <th>
                    Gender
                  </th>
                  <th>
                    Prefer same gender?
                  </th>
                </thead>
                <tbody>
                  <tr>
                    <td>
                      k1763918@kcl.ac.uk
                    </td>
                    <td>
                      Mananchaya
                    </td>
                    <td>
                      Mai
                    </td>
                    <td>
                      Khumtai
                    </td>
                    <td>
                      Cooking
                    </td>
                    <td>
                      Yoga
                    </td>
                    <td>
                      History
                    </td>
                    <td>
                      Japanese
                    </td>
                    <td>
                      Web development
                    </td>
                    <td>
                      Second
                    </td>
                    <td>
                      Female
                    </td>
                    <td>
                      No
                    </td>
                  </tr>
                  <tr>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      Jason
                    </td>
                    <td>
                      Jay
                    </td>
                    <td>
                      Steele
                    </td>
                    <td>
                      Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                      Third
                    </td>
                    <td>
                      Male
                    </td>
                    <td>
                      No
                    </td>
                  </tr>
                  <tr>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      Jason
                    </td>
                    <td>
                      Jay
                    </td>
                    <td>
                      Steele
                    </td>
                    <td>
                      Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                      Third
                    </td>
                    <td>
                      Male
                    </td>
                    <td>
                      No
                    </td>
                  </tr>
                  <tr>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      Jason
                    </td>
                    <td>
                      Jay
                    </td>
                    <td>
                      Steele
                    </td>
                    <td>
                      Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                      Third
                    </td>
                    <td>
                      Male
                    </td>
                    <td>
                      No
                    </td>
                  </tr>
                  <tr>
                    <td>
                      example@kcl.ac.uk
                    </td>
                    <td>
                      Jason
                    </td>
                    <td>
                      Jay
                    </td>
                    <td>
                      Steele
                    </td>
                    <td>
                      Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                    Movies
                    </td>
                    <td>
                      Third
                    </td>
                    <td>
                      Male
                    </td>
                    <td>
                      No
                    </td>
                  </tr>
                </tbody>
              </Table>
              </CardBody>
            </Card>
          </Col>
      </Row>
    </div>
  );
}
}

export default CurrentStudents;